INSERT INTO TRAINING_CENTER ( CENTER_NAME,CENTER_CODE,STUDENT_CAPACITY,CONTACT_EMAIL,CONTACT_PHONE,COURSES,CREATED_ON,ADDRESS_ID) VALUES ( 't1','t desc',3,'t@t.com',123,'CSE,IT',CURRENT_DATE,1);
INSERT INTO ADDRESS ( FULL_ADDRESS,CITY,STATE,PIN) VALUES ( 'a1','Bangalore','Karnataka',123);


