INSERT INTO ADDRESS (id, FULL_ADDRESS,CITY,STATE,PIN) VALUES (1, 'a1','Bangalore','Karnataka',123);

INSERT INTO TRAINING_CENTER (id, CENTER_NAME,CENTER_CODE,STUDENT_CAPACITY,CONTACT_EMAIL,CONTACT_PHONE,COURSES,CREATED_ON,ADDRESS_ID) VALUES ( 1,'t1','t desc',3,'t@t.com',123,'CSE,IT',CURRENT_DATE,1);


